#!/bin/bash

FILE=`expr match "$1" '\(.*\)\..*$'`
EXT=${1/*./}
EXTENSIONS="\(c\|cpp\|cc\|c++\|CC\|C\|CPP\)"
CPPQTPATH=/home/bildgen/cppqt

QT_INCLUDE_PATH=/usr/include/qt5
QT_LIBRARY_PATH=.

if ( expr match "$EXT" "$EXTENSIONS" > /dev/null )
then
    g++ -std=c++11 -O3 -Wall -Wextra -pedantic -fPIC -DQT_NO_VERSION_TAGGING \
        -I. -I$CPPQTPATH \
        -I$QT_INCLUDE_PATH/QtCore -I$QT_INCLUDE_PATH/QtGui \
        -I$QT_INCLUDE_PATH/QtWidgets -I$QT_INCLUDE_PATH $1 -o $FILE \
        -L. -L$CPPQTPATH -ldrawqt \
        -L$QT_LIBRARY_PATH -lQt5Core -lQt5Gui -lQt5Widgets \
        -Wl,-rpath=$QT_LIBRARY_PATH
else
    echo "Falsche Dateiendung! Folgende Dateiendungen sind erlaubt: $EXTENSIONS"
fi
